POST  http://localhost:4444/register
Content-Type: application/json

{
    "name" : "Revanth",
     "email" : "rk2@gmail.com",
      "password" : "1234"
}

###
POST  http://localhost:4444/login
Content-Type: application/json

{
     "email" : "rk2@gmail.com",
      "password" : "1234"
}

### 
POST  http://localhost:4444/logout
Content-Type: application/json
email:rk2@gmail.com
token:eyJhbGciOiJIUzI1NiJ9.cmsyQGdtYWlsLmNvbQ.YScKtud97uHwfBtMfjrZZSC1G5pISDf3CrWQDPSu5XU

###
GET http://localhost:4444/api/emp/20/22
Content-Type: application/json
email:rk2@gmail.com
token:eyJhbGciOiJIUzI1NiJ9.cmsyQGdtYWlsLmNvbQ.YScKtud97uHwfBtMfjrZZSC1G5pISDf3CrWQDPSu5XU

###
GET http://localhost:4444/api/emp/6
Content-Type: application/json
email:rk2@gmail.com
token:eyJhbGciOiJIUzI1NiJ9.cmsyQGdtYWlsLmNvbQ.YScKtud97uHwfBtMfjrZZSC1G5pISDf3CrWQDPSuXU

###
POST  http://localhost:4444/api/emp/add
Content-Type: application/json
email:rk2@gmail.com
token:eyJhbGciOiJIUzI1NiJ9.cmsyQGdtYWlsLmNvbQ.YScKtud97uHwfBtMfjrZZSC1G5pISDf3CrWQDPSu5XU

{
      "Id":17,
      "First_Name":"RK",
      "Last_Name":"Mak",
      "Email":"rk@gmail.com",
      "PhoneNumber":"3456789678"
}

###
Delete http://localhost:4444/api/emp/21
Content-Type: application/json
email:rk2@gmail.com
token:eyJhbGciOiJIUzI1NiJ9.cmsyQGdtYWlsLmNvbQ.YScKtud97uHwfBtMfjrZZSC1G5pISDf3CrWQDPSu5XU
